#
# Rails OMF Server (ROS) Software for visualizing power systems behavior
# Copyright (c) 2015, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/NumericLiterals:
  MinDigits: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'